package codegen

import "text/template"

var fileTemplate = template.Must(template.New("file").Parse(`
// Code generated by golinq. DO NOT EDIT.

package {{.Package}}

import (
    "context"
    "sync"
    "github.com/Neratus/golinq"
    {{- range $alias, $path := .ModelImports}}
    {{$alias}} "{{$path}}"
    {{- end}}
)

{{range .StructDefs}}
{{.}}
{{end}}

{{range .Queries}}
var (
    once{{.Name}}   sync.Once
    cachedSQL{{.Name}} string
    cachedErr{{.Name}} error
)

{{template "queryFunc" .}}
{{end}}
`))

var queryFuncTemplate = template.Must(fileTemplate.New("queryFunc").Parse(`
// {{.Name}} executes a pre-generated query.
func {{.Name}}(ctx context.Context, db *golinq.DB{{range .Params}}, {{.Name}} {{.Type}}{{end}}) ({{.ResultType}}, error) {
    once{{.Name}}.Do(func() {
        ast := {{.ASTLiteral}}
        paramValues := []interface{}{}
        sqlStr, _, err := golinq.Generate(ast, db.Dialect(), paramValues)
        cachedSQL{{.Name}} = sqlStr
        cachedErr{{.Name}} = err
    })
    if cachedErr{{.Name}} != nil {
        return nil, cachedErr{{.Name}}
    }

    actualParams := []interface{}{ {{range $i, $p := .Params}}{{if $i}}, {{end}}{{$p.Name}}{{end}} }
    {{if eq .Method "ToList"}}
    return golinq.QueryRows[{{.ModelType}}](ctx, db, cachedSQL{{.Name}}, actualParams...)
    {{else}}
    return golinq.QueryRow[{{.ModelType}}](ctx, db, cachedSQL{{.Name}}, actualParams...)
    {{end}}
}
`))
