package codegen

import "text/template"

var fileTemplate = template.Must(template.New("file").Parse(`
// Code generated by golinq. DO NOT EDIT.

package {{.Package}}

import (
    "context"
    "sync"
    "github.com/Neratus/golinq"
    {{- range $alias, $path := .ModelImports}}
    {{$alias}} "{{$path}}"
    {{- end}}
)

{{range .StructDefs}}
{{.}}
{{end}}

{{range .Queries}}
var (
    once{{.Name}}   sync.Once
    cachedSQL{{.Name}} string
    cachedErr{{.Name}} error
)

{{template "queryFunc" .}}
{{end}}
`))

var queryFuncTemplate = template.Must(fileTemplate.New("queryFunc").Parse(`
// {{.Name}} executes a pre-generated query.
func {{.Name}}(ctx context.Context, db *golinq.DB{{range .Params}}, {{.Name}} {{.Type}}{{end}}) ({{.ResultType}}, error) {
    onceStmt{{.Name}}.Do(func() {
        ast := {{.ASTLiteral}}
        paramValues := make([]interface{}, {{len .Params}})
        sqlStr, _, err := golinq.Generate(ast, db.Dialect(), paramValues)
        if err != nil {
            stmtErr{{.Name}} = err
            return
        }
        stmt{{.Name}}, err = db.DB().Prepare(sqlStr)
        stmtErr{{.Name}} = err
    })
    if stmtErr{{.Name}} != nil {
        return nil, stmtErr{{.Name}}
    }

    actualParams := []interface{}{ {{range $i, $p := .Params}}{{if $i}}, {{end}}{{$p.Name}}{{end}} }
    rows, err := stmt{{.Name}}.QueryContext(ctx, actualParams...)
    if err != nil {
        return nil, err
    }
    defer rows.Close()

    {{if eq .Method "ToList"}}
    return golinq.ScanRows[{{.ModelType}}](rows)
    {{else}}
    if !rows.Next() {
        if err := rows.Err(); err != nil {
            return nil, err
        }
        return nil, sql.ErrNoRows
    }
    return golinq.ScanRow[{{.ModelType}}](rows)
    {{end}}
}
`))
