// Code generated by golinq. DO NOT EDIT.

package integration

import (
	"context"
	models "golinq/tests/integration/models"

	"github.com/Neratus/golinq"
)

// Query_Getmodels_Country_CountryPopulationHigh_Select executes a pre-generated query.
func Query_Getmodels_Country_CountryPopulationHigh_Select(ctx context.Context, db *golinq.DB) ([]models.Country, error) {
	ast := &golinq.SelectQueryAST{
		SelectFields: []golinq.SelectField{
			{TableAlias: "models.Country", ColumnName: "id"},
			{TableAlias: "models.Country", ColumnName: "name"},
			{TableAlias: "models.Country", ColumnName: "population"},
			{TableAlias: "models.Country", ColumnName: "area"},
		},
		From:  golinq.Relation{Name: "country", Alias: "models.Country"},
		Joins: []golinq.JoinNode{},
		Where: &golinq.ConditionNode{
			Type: golinq.And,
			Children: []*golinq.ConditionNode{
				&golinq.ConditionNode{
					Type:  golinq.Cmp,
					Value: "GT",
					Children: []*golinq.ConditionNode{
						&golinq.ConditionNode{
							Type:  golinq.Field,
							Value: "models.Country.",
						},
						&golinq.ConditionNode{
							Type:  golinq.Const,
							Value: 100000000,
						},
					},
				},
			},
		},
		OrderBy: &golinq.OrderByClause{
			TableAlias: "models.Country",
			Field:      "Population",
			MappingSQL: "population",
			Desc:       true,
		},
		Limit:  0,
		Offset: 0,
		Method: golinq.ToList,
	}
	paramValues := []interface{}{}
	sqlStr, params, err := golinq.Generate(ast, db.Dialect(), paramValues)
	if err != nil {
		return nil, err
	}

	return golinq.QueryRows[models.Country](ctx, db, sqlStr, params...)

}

// Query_Getmodels_Country_CountryCityJoin_Select executes a pre-generated query.
func Query_Getmodels_Country_CountryCityJoin_Select(ctx context.Context, db *golinq.DB) ([]models.Country, error) {
	ast := &golinq.SelectQueryAST{
		SelectFields: []golinq.SelectField{
			{TableAlias: "models.Country", ColumnName: "id"},
			{TableAlias: "models.Country", ColumnName: "name"},
		},
		From: golinq.Relation{Name: "country", Alias: "models.Country"},
		Joins: []golinq.JoinNode{
			{
				Type:  "INNER",
				Left:  nil,
				Right: golinq.Relation{Name: "city", Alias: "City"},
				On: &golinq.ConditionNode{
					Type:  golinq.Cmp,
					Value: "EQ",
					Children: []*golinq.ConditionNode{
						&golinq.ConditionNode{
							Type:  golinq.Field,
							Value: "models.Country.",
						},
						&golinq.ConditionNode{
							Type:  golinq.Field,
							Value: "City.country_id",
						},
					},
				},
			},
		},
		Where: &golinq.ConditionNode{
			Type: golinq.And,
		},
		OrderBy: nil,
		Limit:   0,
		Offset:  0,
		Method:  golinq.ToList,
	}
	paramValues := []interface{}{}
	sqlStr, params, err := golinq.Generate(ast, db.Dialect(), paramValues)
	if err != nil {
		return nil, err
	}

	return golinq.QueryRows[models.Country](ctx, db, sqlStr, params...)

}

// Query_Getmodels_Country_CountryCountryLanguageJoin_CountryLanguageLanguageJoin_Select executes a pre-generated query.
func Query_Getmodels_Country_CountryCountryLanguageJoin_CountryLanguageLanguageJoin_Select(ctx context.Context, db *golinq.DB) ([]models.Country, error) {
	ast := &golinq.SelectQueryAST{
		SelectFields: []golinq.SelectField{
			{TableAlias: "models.Country", ColumnName: "id"},
			{TableAlias: "models.Country", ColumnName: "name"},
		},
		From: golinq.Relation{Name: "country", Alias: "models.Country"},
		Joins: []golinq.JoinNode{
			{
				Type:  "INNER",
				Left:  nil,
				Right: golinq.Relation{Name: "country_language", Alias: "CountryLanguage"},
				On: &golinq.ConditionNode{
					Type:  golinq.Cmp,
					Value: "EQ",
					Children: []*golinq.ConditionNode{
						&golinq.ConditionNode{
							Type:  golinq.Field,
							Value: "models.Country.",
						},
						&golinq.ConditionNode{
							Type:  golinq.Field,
							Value: "CountryLanguage.country_id",
						},
					},
				},
			},
			{
				Type:  "INNER",
				Left:  nil,
				Right: golinq.Relation{Name: "language", Alias: "Language"},
				On: &golinq.ConditionNode{
					Type:  golinq.Cmp,
					Value: "EQ",
					Children: []*golinq.ConditionNode{
						&golinq.ConditionNode{
							Type:  golinq.Field,
							Value: "CountryLanguage.language_id",
						},
						&golinq.ConditionNode{
							Type:  golinq.Field,
							Value: "Language.id",
						},
					},
				},
			},
		},
		Where: &golinq.ConditionNode{
			Type: golinq.And,
		},
		OrderBy: nil,
		Limit:   0,
		Offset:  0,
		Method:  golinq.ToList,
	}
	paramValues := []interface{}{}
	sqlStr, params, err := golinq.Generate(ast, db.Dialect(), paramValues)
	if err != nil {
		return nil, err
	}

	return golinq.QueryRows[models.Country](ctx, db, sqlStr, params...)

}
